package com.fireway.backend.shared.exception;
public enum ErrorCode { NOT_FOUND, VALIDATION_ERROR, CONFLICT, UNAUTHORIZED, EXTERNAL_SYSTEM_ERROR, INFRASTRUCTURE_ERROR, MALFORMED_REQUEST, INTERNAL_ERROR }
