package team.fireway.goldenlane.shared.exception;
public enum ErrorCode { NOT_FOUND, VALIDATION_FAILED, CONFLICT, UNAUTHORIZED, EXTERNAL_SYSTEM_ERROR, INFRASTRUCTURE_ERROR, INVALID_REQUEST, INTERNAL_ERROR, ROUTE_NOT_FOUND }

